// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG_H7ohv3uiKGG4Z6gmyqXMADnURoyzFQ',
    appId: '1:165935469759:web:35f672c0d6756b1a3ae20a',
    messagingSenderId: '165935469759',
    projectId: 'flutteruitemplate',
    authDomain: 'flutteruitemplate.firebaseapp.com',
    storageBucket: 'flutteruitemplate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc-_KDEL-6KqQhSgbpEtlOjOQBILDOE5o',
    appId: '1:165935469759:android:6a2d4cbac20dfbe03ae20a',
    messagingSenderId: '165935469759',
    projectId: 'flutteruitemplate',
    storageBucket: 'flutteruitemplate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxL1xLKIwv9Rz_JP81pKvMYwAYNWgF8a4',
    appId: '1:165935469759:ios:34e220d84189983c3ae20a',
    messagingSenderId: '165935469759',
    projectId: 'flutteruitemplate',
    storageBucket: 'flutteruitemplate.appspot.com',
    iosBundleId: 'com.example.authenticationTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxL1xLKIwv9Rz_JP81pKvMYwAYNWgF8a4',
    appId: '1:165935469759:ios:81df19699787cdd33ae20a',
    messagingSenderId: '165935469759',
    projectId: 'flutteruitemplate',
    storageBucket: 'flutteruitemplate.appspot.com',
    iosBundleId: 'com.example.authenticationTemplate.RunnerTests',
  );
}
